// ==========================
// GOLDEN CANDYS
// ==========================

// Chance da Mensagem Dourada.
// Quanto maior o número, mais rara ela será.
// 50 = aproximadamente 1 chance em 50.
const CHANCE_MENSAGEM_DOURADA = 50;

// Frases (PARTE 1 - 100)
const frases = [

{numero:1,texto:"Que seu dia seja tão doce quanto este brigadeiro. 🤍"},
{numero:2,texto:"Você é mais forte do que imagina. 💛"},
{numero:3,texto:"Nunca desista dos seus sonhos. ✨"},
{numero:4,texto:"Deus está preparando algo lindo para você. 🙏"},
{numero:5,texto:"Continue caminhando. O melhor ainda está por vir. 🌸"},
{numero:6,texto:"Seu sorriso ilumina o mundo. 😊"},
{numero:7,texto:"Tudo coopera para o bem daqueles que amam a Deus. ❤️"},
{numero:8,texto:"Você merece viver coisas incríveis. 🌻"},
{numero:9,texto:"A esperança sempre vence o medo. 🤍"},
{numero:10,texto:"Confie no tempo de Deus. ⏳"},
{numero:11,texto:"Acredite: grandes coisas começam com pequenos passos. 🌷"},
{numero:12,texto:"Hoje pode ser o começo de algo extraordinário. ✨"},
{numero:13,texto:"Nunca deixe de acreditar em você. 💛"},
{numero:14,texto:"Você é capaz de conquistar muito mais do que imagina. 🌻"},
{numero:15,texto:"Que a paz acompanhe cada momento do seu dia. 🤍"},
{numero:16,texto:"Respire fundo. Deus continua no controle. 🙏"},
{numero:17,texto:"Seu esforço de hoje será sua vitória amanhã. 💪"},
{numero:18,texto:"Espalhe gentileza por onde passar. 😊"},
{numero:19,texto:"Você é luz na vida de alguém. ✨"},
{numero:20,texto:"O impossível é apenas uma oportunidade para Deus agir. ❤️"},
{numero:21,texto:"Nunca perca a esperança. 🌸"},
{numero:22,texto:"Você nasceu para viver grandes histórias. 📖"},
{numero:23,texto:"Cada novo dia é um presente. 🎁"},
{numero:24,texto:"Sua coragem inspira pessoas ao seu redor. 🌷"},
{numero:25,texto:"Confie mais em Deus e menos no medo. 🙏"},
{numero:26,texto:"Que seu coração permaneça leve. 🤍"},
{numero:27,texto:"Tudo acontece no tempo certo. ⏳"},
{numero:28,texto:"Você é mais amado do que imagina. ❤️"},
{numero:29,texto:"Os melhores capítulos da sua vida ainda serão escritos. 📚"},
{numero:30,texto:"Deus nunca esquece dos seus sonhos. ✨"},
{numero:31,texto:"Hoje é um ótimo dia para recomeçar. 🌻"},
{numero:32,texto:"Sorria. Seu sorriso faz diferença. 😊"},
{numero:33,texto:"A bondade sempre volta para quem a pratica. 🤎"},
{numero:34,texto:"Continue firme. Você está mais perto da vitória. 💪"},
{numero:35,texto:"Que nunca falte fé em seu coração. 🙏"},
{numero:36,texto:"A felicidade mora nas pequenas coisas. 🍫"},
{numero:37,texto:"Você consegue superar qualquer desafio. 💛"},
{numero:38,texto:"O amor sempre será a melhor escolha. ❤️"},
{numero:39,texto:"Grandes milagres começam com pequenas orações. ✨"},
{numero:40,texto:"Você foi criado com um propósito especial. 🌸"},
{numero:41,texto:"Seja motivo de alegria para alguém hoje. 😊"},
{numero:42,texto:"Nunca desista daquilo que faz seu coração sorrir. 🤍"},
{numero:43,texto:"A gratidão transforma tudo. 🌷"},
{numero:44,texto:"A cada amanhecer nasce uma nova oportunidade. 🌅"},
{numero:45,texto:"Você é precioso aos olhos de Deus. 🙏"},
{numero:46,texto:"As melhores surpresas chegam sem aviso. 🎁"},
{numero:47,texto:"Confiança é plantar hoje para colher amanhã. 🌱"},
{numero:48,texto:"Você é mais forte do que qualquer dificuldade. 💪"},
{numero:49,texto:"Que a alegria faça morada em sua vida. 🤍"},
{numero:50,texto:"O bem que você faz sempre encontra o caminho de volta. ❤️"},
{numero:51,texto:"Seja paciente. O melhor está chegando. 🌻"},
{numero:52,texto:"Sua história ainda está sendo escrita. 📖"},
{numero:53,texto:"Nunca subestime o poder de um sorriso. 😊"},
{numero:54,texto:"Deus conhece cada detalhe da sua caminhada. 🙏"},
{numero:55,texto:"O amor vence qualquer medo. ❤️"},
{numero:56,texto:"A esperança é uma escolha diária. ✨"},
{numero:57,texto:"Você já venceu muitas batalhas. Continue. 💛"},
{numero:58,texto:"O hoje é uma oportunidade de ser feliz. 🌸"},
{numero:59,texto:"Acredite no impossível. 🤍"},
{numero:60,texto:"Você é um presente para este mundo. 🎁"},
{numero:61,texto:"Toda tempestade passa. ☀️"},
{numero:62,texto:"A bondade nunca sai de moda. 🌷"},
{numero:63,texto:"Seu coração é maior que qualquer obstáculo. ❤️"},
{numero:64,texto:"Permita-se sonhar grande. ✨"},
{numero:65,texto:"Você está exatamente onde precisa estar. 🌻"},
{numero:66,texto:"A fé move montanhas. 🙏"},
{numero:67,texto:"A alegria compartilhada se multiplica. 😊"},
{numero:68,texto:"Nunca deixe sua luz apagar. 💡"},
{numero:69,texto:"O melhor investimento é acreditar em você. 💛"},
{numero:70,texto:"Deus abre portas que ninguém pode fechar. 🚪"},
{numero:71,texto:"Que seu dia seja repleto de paz. 🤍"},
{numero:72,texto:"A felicidade começa dentro de você. 🌸"},
{numero:73,texto:"Seja luz por onde passar. ✨"},
{numero:74,texto:"Cada passo vale a pena. 👣"},
{numero:75,texto:"Você é mais corajoso do que imagina. 💪"},
{numero:76,texto:"O amor de Deus nunca falha. ❤️"},
{numero:77,texto:"Tudo tem um propósito. 🙏"},
{numero:78,texto:"Sua determinação inspira. 🌻"},
{numero:79,texto:"Continue acreditando. 🤍"},
{numero:80,texto:"Hoje será um lindo dia. ☀️"},
{numero:81,texto:"Nunca deixe de espalhar amor. ❤️"},
{numero:82,texto:"Você pode recomeçar quantas vezes precisar. 🌷"},
{numero:83,texto:"O impossível se torna possível pela fé. ✨"},
{numero:84,texto:"Deus cuida até dos detalhes. 🙏"},
{numero:85,texto:"Seu futuro é promissor. 💛"},
{numero:86,texto:"O amor sempre encontra um caminho. 🤎"},
{numero:87,texto:"Você nasceu para brilhar. ⭐"},
{numero:88,texto:"Que nunca falte esperança. 🌸"},
{numero:89,texto:"A vida é mais doce quando compartilhamos alegria. 🍫"},
{numero:90,texto:"Você faz diferença no mundo. 🌍"},
{numero:91,texto:"Continue firme. Deus está com você. 🙏"},
{numero:92,texto:"Semeie amor e colha felicidade. ❤️"},
{numero:93,texto:"Os melhores dias ainda virão. 🌷"},
{numero:94,texto:"Você é capaz de realizar seus sonhos. ✨"},
{numero:95,texto:"Toda conquista começa com um passo. 👣"},
{numero:96,texto:"Confie no processo. 🌻"},
{numero:97,texto:"Que Deus abençoe seu caminho. 🤍"},
{numero:98,texto:"Seu sorriso pode mudar o dia de alguém. 😊"},
{numero:99,texto:"Você é um milagre vivendo grandes possibilidades. 💛"},
{numero:100,texto:"Obrigado por fazer parte da família Golden Candys! 🍫❤️"},
  {numero:101,texto:"Você não precisa ter tudo resolvido para continuar. 🌷"},
{numero:102,texto:"Deus sabe exatamente onde te encontrar. 🙏"},
{numero:103,texto:"Coisas bonitas também levam tempo. ✨"},
{numero:104,texto:"Seu jeito de ser faz falta no mundo. 🤍"},
{numero:105,texto:"Não compare seu começo com o meio de alguém. 🌱"},
{numero:106,texto:"Que hoje você se lembre do quanto é especial. 💛"},
{numero:107,texto:"A paz também é uma forma de vitória. 🕊️"},
{numero:108,texto:"Continue. Até os pequenos passos te levam adiante. 👣"},
{numero:109,texto:"Deus não perdeu o controle da sua história. 🙏"},
{numero:110,texto:"Você merece se tratar com mais carinho. 🌸"},
{numero:111,texto:"Nem todo dia precisa ser perfeito para ser bom. ☀️"},
{numero:112,texto:"A sua presença torna alguns lugares melhores. ✨"},
{numero:113,texto:"Respire. Você não precisa carregar tudo sozinho. 🤍"},
{numero:114,texto:"Existe força até na sua delicadeza. 🌷"},
{numero:115,texto:"O que hoje parece demora pode ser proteção. 🙏"},
{numero:116,texto:"Sua caminhada tem valor, mesmo quando ninguém vê. 💛"},
{numero:117,texto:"Você é digno de amor, cuidado e respeito. ❤️"},
{numero:118,texto:"Não tenha medo de florescer no seu próprio tempo. 🌻"},
{numero:119,texto:"A sua história não termina em um dia difícil. 📖"},
{numero:120,texto:"Deus ainda pode surpreender você. ✨"},
{numero:121,texto:"Você não chegou até aqui por acaso. 🤍"},
{numero:122,texto:"Seu coração também merece descanso. 🕊️"},
{numero:123,texto:"Há beleza em continuar tentando. 🌱"},
{numero:124,texto:"Você pode ir devagar, só não precisa desistir. 👣"},
{numero:125,texto:"A fé começa onde o medo perde a voz. 🙏"},
{numero:126,texto:"Que você encontre motivos simples para sorrir hoje. 😊"},
{numero:127,texto:"Sua luz não diminui quando outra pessoa brilha. ✨"},
{numero:128,texto:"Aquilo que é seu encontrará o caminho até você. 🌷"},
{numero:129,texto:"Não se cobre tanto. Você também está aprendendo. 🤍"},
{numero:130,texto:"Deus transforma caminhos difíceis em testemunhos lindos. 🙏"},
{numero:131,texto:"Você é mais preparado do que pensa. 💛"},
{numero:132,texto:"A sua gentileza pode mudar o dia de alguém. 🌸"},
{numero:133,texto:"Toda manhã traz uma nova chance. ☀️"},
{numero:134,texto:"Você não precisa diminuir seus sonhos para caber em lugares pequenos. ✨"},
{numero:135,texto:"O tempo certo também é uma bênção. ⏳"},
{numero:136,texto:"Que nunca falte coragem para começar de novo. 🌱"},
{numero:137,texto:"Deus ouve até as orações que saem em silêncio. 🙏"},
{numero:138,texto:"Você merece celebrar cada pequena conquista. 🎉"},
{numero:139,texto:"Há dias bons esperando por você. 🤍"},
{numero:140,texto:"Seja paciente com a pessoa que você está se tornando. 🌷"},
{numero:141,texto:"O seu valor não depende da opinião de ninguém. 💛"},
{numero:142,texto:"A calma também constrói grandes coisas. 🕊️"},
{numero:143,texto:"Você pode ser o recomeço que estava esperando. ✨"},
{numero:144,texto:"Nem todo atraso é perda. Às vezes, é livramento. 🙏"},
{numero:145,texto:"Seu sonho merece mais uma tentativa. 🌻"},
{numero:146,texto:"Não esqueça de agradecer pela pessoa que você já se tornou. 🤍"},
{numero:147,texto:"Você é capaz de criar uma vida da qual se orgulhe. 💫"},
{numero:148,texto:"Seu coração ainda viverá momentos muito felizes. ❤️"},
{numero:149,texto:"Confie: Deus trabalha mesmo quando você não vê. 🙏"},
{numero:150,texto:"Acredite na beleza dos novos começos. 🌸"},
{numero:151,texto:"Você não precisa provar seu valor o tempo todo. 🤍"},
{numero:152,texto:"A sua melhor fase ainda pode estar começando. ✨"},
{numero:153,texto:"Dê espaço para coisas boas acontecerem. 🌷"},
{numero:154,texto:"Todo esforço feito com amor deixa frutos. 🌱"},
{numero:155,texto:"Deus conhece os desejos mais sinceros do seu coração. 🙏"},
{numero:156,texto:"Você pode fazer hoje ser mais leve. ☀️"},
{numero:157,texto:"Sua vida tem propósito até nos dias confusos. 💛"},
{numero:158,texto:"Não abandone quem você é para agradar os outros. 🤍"},
{numero:159,texto:"Você merece estar perto de quem valoriza sua presença. ❤️"},
{numero:160,texto:"A esperança floresce quando você decide continuar. 🌻"},
{numero:161,texto:"Talvez o que você procura esteja mais perto do que imagina. ✨"},
{numero:162,texto:"Deus é especialista em transformar finais em recomeços. 🙏"},
{numero:163,texto:"Não tenha vergonha de começar pequeno. 🌱"},
{numero:164,texto:"Seu sorriso é um detalhe bonito deste mundo. 😊"},
{numero:165,texto:"As coisas certas não precisam roubar sua paz. 🕊️"},
{numero:166,texto:"Você pode descansar sem desistir. 🤍"},
{numero:167,texto:"O amanhã pode trazer respostas que hoje você ainda não tem. 🌷"},
{numero:168,texto:"Deus cuida de você de maneiras que nem sempre percebe. 🙏"},
{numero:169,texto:"Seu caminho não precisa ser igual ao de ninguém. 👣"},
{numero:170,texto:"Você merece viver um amor que traga segurança. ❤️"},
{numero:171,texto:"Permita-se comemorar o quanto já evoluiu. ✨"},
{numero:172,texto:"Não deixe um momento ruim definir um dia inteiro. ☀️"},
{numero:173,texto:"Você tem dentro de si tudo o que precisa para começar. 💛"},
{numero:174,texto:"Há força em escolher a paz. 🕊️"},
{numero:175,texto:"Deus pode fazer além do que você consegue imaginar. 🙏"},
{numero:176,texto:"Você não está atrasado. Está construindo sua própria história. 📖"},
{numero:177,texto:"Que o seu coração encontre tranquilidade hoje. 🤍"},
{numero:178,texto:"Um passo de cada vez também é progresso. 👣"},
{numero:179,texto:"Coisas lindas acontecem quando você não desiste de si. 🌸"},
{numero:180,texto:"Sua existência já é motivo de gratidão. ✨"},
{numero:181,texto:"Deus não ignora nenhuma lágrima sua. 🙏"},
{numero:182,texto:"Você pode aprender sem se culpar por ainda não saber. 🌱"},
{numero:183,texto:"Não tenha medo de escolher o que faz bem para você. 🤍"},
{numero:184,texto:"Sua voz merece ser ouvida. 💛"},
{numero:185,texto:"O amor verdadeiro também sabe cuidar. ❤️"},
{numero:186,texto:"Você ainda viverá respostas de orações antigas. 🙏"},
{numero:187,texto:"A vida pode surpreender você de um jeito bonito. 🌷"},
{numero:188,texto:"Continue plantando, mesmo que ainda não veja os frutos. 🌱"},
{numero:189,texto:"Você merece uma rotina que também tenha alegria. ☀️"},
{numero:190,texto:"Há algo de muito especial no seu jeito de existir. ✨"},
{numero:191,texto:"Deus está presente até nos dias silenciosos. 🙏"},
{numero:192,texto:"Não se abandone para ser aceito. 🤍"},
{numero:193,texto:"Sua paz vale mais do que provar que está certo. 🕊️"},
{numero:194,texto:"Você pode transformar medo em movimento. 💛"},
{numero:195,texto:"O que é feito com verdade toca o coração. ❤️"},
{numero:196,texto:"Você ainda tem muitos motivos para acreditar. 🌻"},
{numero:197,texto:"Deus prepara caminhos onde você só enxerga obstáculos. 🙏"},
{numero:198,texto:"Hoje, escolha falar com você com mais amor. 🌸"},
{numero:199,texto:"Seu futuro não está limitado pelo seu passado. ✨"},
{numero:200,texto:"Mais um brigadeiro, mais uma lembrança: você é especial para a Golden Candys. 🍫💛"},
  {numero:201,texto:"Hoje é um ótimo dia para acreditar de novo. ☀️"},
{numero:202,texto:"Você é mais resiliente do que imagina. 💛"},
{numero:203,texto:"Que nunca lhe faltem motivos para sorrir. 😊"},
{numero:204,texto:"A fé torna o caminho mais leve. 🙏"},
{numero:205,texto:"Você tem potencial para realizar grandes sonhos. ✨"},
{numero:206,texto:"Grandes mudanças começam com pequenas atitudes. 🌱"},
{numero:207,texto:"Seu coração merece paz. 🤍"},
{numero:208,texto:"Você já venceu desafios que pareciam impossíveis. 💪"},
{numero:209,texto:"O melhor ainda está sendo preparado. 🌸"},
{numero:210,texto:"Continue semeando bondade. ❤️"},
{numero:211,texto:"Sua história inspira mais pessoas do que você imagina. 📖"},
{numero:212,texto:"Nunca deixe de acreditar no amor. ❤️"},
{numero:213,texto:"Você faz diferença onde está. 🌍"},
{numero:214,texto:"A esperança sempre encontra um caminho. ✨"},
{numero:215,texto:"Cada amanhecer é uma nova oportunidade. ☀️"},
{numero:216,texto:"Deus cuida dos detalhes da sua vida. 🙏"},
{numero:217,texto:"Seu esforço será recompensado. 🌻"},
{numero:218,texto:"Permita-se viver momentos felizes. 🤍"},
{numero:219,texto:"Você merece celebrar suas conquistas. 🎉"},
{numero:220,texto:"Nunca pare de sonhar. ✨"},
{numero:221,texto:"A felicidade mora nas pequenas coisas. 🍫"},
{numero:222,texto:"Você tem uma luz única. 💡"},
{numero:223,texto:"Seja paciente consigo mesmo. 🌷"},
{numero:224,texto:"Grandes vitórias levam tempo. ⏳"},
{numero:225,texto:"A bondade transforma vidas. ❤️"},
{numero:226,texto:"Você nasceu para florescer. 🌸"},
{numero:227,texto:"A coragem cresce a cada passo. 👣"},
{numero:228,texto:"Deus nunca abandona quem confia Nele. 🙏"},
{numero:229,texto:"Você é motivo de orgulho. 💛"},
{numero:230,texto:"O amor sempre vale a pena. ❤️"},
{numero:231,texto:"Hoje pode ser o começo da sua melhor fase. ☀️"},
{numero:232,texto:"Continue acreditando em dias melhores. ✨"},
{numero:233,texto:"Você merece viver em paz. 🤍"},
{numero:234,texto:"Nunca subestime sua força. 💪"},
{numero:235,texto:"Deus está escrevendo uma linda história para você. 📖"},
{numero:236,texto:"Seu coração é mais forte que qualquer medo. ❤️"},
{numero:237,texto:"Sorria. O mundo precisa da sua alegria. 😊"},
{numero:238,texto:"Você é muito especial. 💛"},
{numero:239,texto:"A gratidão muda tudo. 🌷"},
{numero:240,texto:"Não desista agora. 🌻"},
{numero:241,texto:"Você é amado por Deus. 🙏"},
{numero:242,texto:"Toda caminhada começa com um primeiro passo. 👣"},
{numero:243,texto:"Sua fé pode mover montanhas. ⛰️"},
{numero:244,texto:"A vida reserva boas surpresas. 🎁"},
{numero:245,texto:"Você merece dias leves. 🤍"},
{numero:246,texto:"Continue fazendo o bem. ❤️"},
{numero:247,texto:"A esperança renasce todos os dias. ☀️"},
{numero:248,texto:"Nunca perca sua essência. ✨"},
{numero:249,texto:"Seu futuro é cheio de possibilidades. 🌸"},
{numero:250,texto:"Você está exatamente onde precisa estar. 🌱"},
{numero:251,texto:"Cada dia é uma nova chance. 🌷"},
{numero:252,texto:"Sua determinação abrirá portas. 🚪"},
{numero:253,texto:"Confie no processo. 🙏"},
{numero:254,texto:"Você é capaz de superar qualquer desafio. 💪"},
{numero:255,texto:"A felicidade também está no caminho. 🤍"},
{numero:256,texto:"Grandes sonhos começam pequenos. ✨"},
{numero:257,texto:"O amor é sempre a melhor resposta. ❤️"},
{numero:258,texto:"Você pode mais do que imagina. 💛"},
{numero:259,texto:"Não tenha medo de recomeçar. 🌻"},
{numero:260,texto:"Deus continua trabalhando por você. 🙏"},
{numero:261,texto:"Você faz o mundo mais bonito. 🌍"},
{numero:262,texto:"Acredite em milagres. ✨"},
{numero:263,texto:"Nunca é tarde para um novo começo. 🌱"},
{numero:264,texto:"Sua paz vale ouro. 🤍"},
{numero:265,texto:"Continue firme. 💪"},
{numero:266,texto:"Você é mais corajoso do que pensa. 🌸"},
{numero:267,texto:"O impossível pode acontecer. 🙏"},
{numero:268,texto:"Que seu dia seja cheio de alegria. 😊"},
{numero:269,texto:"Tudo passa, inclusive os dias difíceis. ☀️"},
{numero:270,texto:"Você nasceu para vencer. 🏆"},
{numero:271,texto:"Nunca deixe de acreditar em Deus. 🙏"},
{numero:272,texto:"Seu sorriso ilumina vidas. 💛"},
{numero:273,texto:"A paz começa dentro de você. 🤍"},
{numero:274,texto:"Você é um presente para alguém. 🎁"},
{numero:275,texto:"O melhor ainda está por vir. ✨"},
{numero:276,texto:"Continue cultivando esperança. 🌷"},
{numero:277,texto:"Seu esforço não será em vão. 🌻"},
{numero:278,texto:"A bondade sempre encontra o caminho de volta. ❤️"},
{numero:279,texto:"Você é capaz de grandes conquistas. 💪"},
{numero:280,texto:"Deus faz infinitamente mais. 🙏"},
{numero:281,texto:"Hoje escolha ser feliz. ☀️"},
{numero:282,texto:"Você é forte, mesmo quando não percebe. 💛"},
{numero:283,texto:"Nunca perca sua fé. 🙏"},
{numero:284,texto:"Você merece viver seus sonhos. ✨"},
{numero:285,texto:"A alegria também é uma escolha. 😊"},
{numero:286,texto:"Você inspira pessoas. 🌸"},
{numero:287,texto:"O amor transforma corações. ❤️"},
{numero:288,texto:"Continue olhando para frente. 👣"},
{numero:289,texto:"Tudo acontece no tempo certo. ⏳"},
{numero:290,texto:"Você já é uma vitória. 🤍"},
{numero:291,texto:"Seja luz onde estiver. 💡"},
{numero:292,texto:"Grandes histórias ainda serão vividas. 📖"},
{numero:293,texto:"A esperança nunca decepciona. 🌻"},
{numero:294,texto:"Confie mais em Deus. 🙏"},
{numero:295,texto:"Seu futuro será incrível. ✨"},
{numero:296,texto:"A felicidade está mais perto do que parece. 💛"},
{numero:297,texto:"Nunca pare de acreditar em você. 🌷"},
{numero:298,texto:"Você é único e insubstituível. 🤍"},
{numero:299,texto:"Obrigado por adoçar seu dia com a Golden Candys! 🍫"},
{numero:300,texto:"Que Deus abençoe sua vida hoje e sempre. 🙏"},
  {numero:301,texto:"Você merece viver dias extraordinários. ✨"},
{numero:302,texto:"Nunca duvide do plano que Deus tem para você. 🙏"},
{numero:303,texto:"Que seu coração esteja cheio de paz hoje. 🤍"},
{numero:304,texto:"Toda conquista começa com coragem. 💪"},
{numero:305,texto:"Acredite: coisas incríveis estão chegando. 🌸"},
{numero:306,texto:"Seu valor não depende da opinião dos outros. 💛"},
{numero:307,texto:"Continue sendo luz por onde passar. 💡"},
{numero:308,texto:"O amor sempre encontra um caminho. ❤️"},
{numero:309,texto:"Você já é mais forte do que era ontem. 🌱"},
{numero:310,texto:"Deus nunca se atrasa. ⏳"},
{numero:311,texto:"Você é uma bênção na vida de alguém. 🤍"},
{numero:312,texto:"A felicidade também mora nas pequenas vitórias. 🎉"},
{numero:313,texto:"Hoje pode ser o dia da sua resposta. 🙏"},
{numero:314,texto:"Nunca deixe de acreditar em milagres. ✨"},
{numero:315,texto:"Você inspira mais pessoas do que imagina. 🌷"},
{numero:316,texto:"Que nunca falte esperança na sua caminhada. 🌻"},
{numero:317,texto:"Respire fundo. Tudo vai ficar bem. 🤍"},
{numero:318,texto:"Você nasceu para florescer. 🌸"},
{numero:319,texto:"A paz vale mais que qualquer discussão. 🕊️"},
{numero:320,texto:"Seu sorriso faz diferença no mundo. 😊"},
{numero:321,texto:"Que Deus fortaleça cada passo seu. 🙏"},
{numero:322,texto:"Você pode ir muito mais longe. 🚀"},
{numero:323,texto:"Os melhores capítulos ainda estão por vir. 📖"},
{numero:324,texto:"Nunca tenha vergonha de recomeçar. 🌱"},
{numero:325,texto:"Você merece viver tudo aquilo que sonha. 💛"},
{numero:326,texto:"A gratidão abre portas. 🚪"},
{numero:327,texto:"Sua fé é maior que qualquer obstáculo. 🙏"},
{numero:328,texto:"Continue firme. Você está evoluindo. 💪"},
{numero:329,texto:"O amanhã guarda lindas surpresas. 🌷"},
{numero:330,texto:"Você é muito importante. 🤍"},
{numero:331,texto:"Nunca deixe de espalhar gentileza. ❤️"},
{numero:332,texto:"Grandes coisas levam tempo para acontecer. ⏳"},
{numero:333,texto:"Você é capaz de transformar sua história. ✨"},
{numero:334,texto:"Que seu dia seja doce em todos os sentidos. 🍫"},
{numero:335,texto:"Deus conhece o seu coração. 🙏"},
{numero:336,texto:"Você já venceu muita coisa. Continue. 🌻"},
{numero:337,texto:"Hoje escolha acreditar. 💛"},
{numero:338,texto:"Toda tempestade passa. ☀️"},
{numero:339,texto:"Você merece dias tranquilos. 🤍"},
{numero:340,texto:"Nunca desista dos seus sonhos. 🌸"},
{numero:341,texto:"Seu esforço será recompensado. 🌱"},
{numero:342,texto:"O amor de Deus nunca falha. ❤️"},
{numero:343,texto:"Continue plantando o bem. 🌷"},
{numero:344,texto:"Você ainda viverá grandes conquistas. 🏆"},
{numero:345,texto:"Que nunca lhe falte coragem. 💪"},
{numero:346,texto:"Você ilumina ambientes. 💡"},
{numero:347,texto:"Tudo coopera para o bem daqueles que amam a Deus. 🙏"},
{numero:348,texto:"Hoje sorria mais. 😊"},
{numero:349,texto:"Sua presença faz diferença. 🤍"},
{numero:350,texto:"A felicidade também está nas pequenas coisas. 🌸"},
{numero:351,texto:"Obrigado por escolher a Golden Candys. 🍫"},
{numero:352,texto:"Cada brigadeiro leva um pedacinho de carinho. ❤️"},
{numero:353,texto:"Esperamos ter adoçado seu dia. 🤎"},
{numero:354,texto:"A vida fica mais gostosa quando compartilhamos momentos. 🍫"},
{numero:355,texto:"Você acabou de ganhar um sorriso nosso. 😊"},
{numero:356,texto:"Volte sempre para descobrir novas mensagens! ✨"},
{numero:357,texto:"Será que na próxima vem a Mensagem Dourada? 👑"},
{numero:358,texto:"Quem espalha doçura recebe doçura. 🍫"},
{numero:359,texto:"Sua visita alegrou o nosso dia. 🤍"},
{numero:360,texto:"Golden Candys deseja muitas alegrias para você! 💛"},
{numero:361,texto:"Continue colecionando momentos doces. 🍬"},
{numero:362,texto:"Hoje o brigadeiro encontrou a pessoa certa: você! 🍫"},
{numero:363,texto:"Você acabou de desbloquear um sorriso. 😊"},
{numero:364,texto:"A vida é mais doce com gratidão. 🌷"},
{numero:365,texto:"Obrigado por fazer parte da nossa história. 🤎"},
{numero:366,texto:"Que nunca faltem doces lembranças. 🍫"},
{numero:367,texto:"A Golden Candys acredita em você. 💛"},
{numero:368,texto:"Que seu dia tenha sabor de felicidade. 🌸"},
{numero:369,texto:"Compartilhe um brigadeiro com alguém especial. ❤️"},
{numero:370,texto:"Doce é dividir momentos felizes. 🍫"},
{numero:371,texto:"Você faz parte da família Golden Candys. 🤍"},
{numero:372,texto:"Hoje é um bom dia para agradecer. 🙏"},
{numero:373,texto:"Seu coração merece leveza. 🕊️"},
{numero:374,texto:"Nunca pare de sonhar grande. ✨"},
{numero:375,texto:"O impossível é apenas o começo de um milagre. 🙏"},
{numero:376,texto:"Você nasceu para vencer. 🏆"},
{numero:377,texto:"Sua jornada vale a pena. 👣"},
{numero:378,texto:"Deus já está preparando o próximo capítulo. 📖"},
{numero:379,texto:"A esperança nunca sai de moda. 🌻"},
{numero:380,texto:"Você é incrível exatamente como é. 💛"},
{numero:381,texto:"Sorria, você acabou de ganhar uma mensagem exclusiva. 🍫"},
{numero:382,texto:"Cada dia é uma nova oportunidade de ser feliz. ☀️"},
{numero:383,texto:"O amor transforma tudo. ❤️"},
{numero:384,texto:"A paz começa dentro de você. 🤍"},
{numero:385,texto:"Nunca deixe de acreditar em si mesmo. ✨"},
{numero:386,texto:"Você é mais forte que seus medos. 💪"},
{numero:387,texto:"A vida recompensa quem persevera. 🌱"},
{numero:388,texto:"Deus cuida até do que você não percebe. 🙏"},
{numero:389,texto:"Você merece celebrar cada pequena vitória. 🎉"},
{numero:390,texto:"Continue brilhando. ⭐"},
{numero:391,texto:"Sua felicidade importa. 💛"},
{numero:392,texto:"Obrigado por escanear este QR Code! 📱"},
{numero:393,texto:"Esperamos ver você novamente em breve. 🍫"},
{numero:394,texto:"Que seu dia seja repleto de bênçãos. 🙏"},
{numero:395,texto:"Nunca perca sua essência. 🤍"},
{numero:396,texto:"Você faz o mundo melhor sendo quem é. 🌍"},
{numero:397,texto:"Leve essa mensagem com carinho. ❤️"},
{numero:398,texto:"Até o próximo brigadeiro! 🍫"},
{numero:399,texto:"Continue espalhando alegria por onde passar. 😊"},
{numero:400,texto:"Parabéns! Você chegou à mensagem número 400. 🎉"},
  {numero:401,texto:"Você acabou de encontrar uma das mensagens mais raras da Golden Candys! 🍫✨"},
{numero:402,texto:"Hoje é um ótimo dia para sorrir mais. 😊"},
{numero:403,texto:"Nunca subestime o poder de um coração grato. 🤍"},
{numero:404,texto:"Deus continua escrevendo sua história. 🙏"},
{numero:405,texto:"Seu melhor ainda está por vir. 🌸"},
{numero:406,texto:"Espalhe amor por onde passar. ❤️"},
{numero:407,texto:"Você merece viver dias inesquecíveis. 💛"},
{numero:408,texto:"O impossível pode acontecer. ✨"},
{numero:409,texto:"Nunca pare de acreditar. 🌷"},
{numero:410,texto:"Seu sorriso ilumina o mundo. ☀️"},
{numero:411,texto:"A Golden Candys deseja um dia doce para você. 🍫"},
{numero:412,texto:"Você é muito mais forte do que pensa. 💪"},
{numero:413,texto:"Cada novo dia traz novas oportunidades. 🌱"},
{numero:414,texto:"Deus nunca falha. 🙏"},
{numero:415,texto:"Você faz diferença na vida de alguém. 🤍"},
{numero:416,texto:"A felicidade está nas pequenas coisas. 🌸"},
{numero:417,texto:"Nunca deixe de sonhar. ✨"},
{numero:418,texto:"Hoje pode ser o início da sua melhor fase. 🌻"},
{numero:419,texto:"Você é uma bênção. ❤️"},
{numero:420,texto:"Continue caminhando. 👣"},
{numero:421,texto:"Obrigado por escolher a Golden Candys! 🍫"},
{numero:422,texto:"Seu dia ficou mais doce, e esperamos que mais feliz também. 😊"},
{numero:423,texto:"Você é especial exatamente como é. 💛"},
{numero:424,texto:"Confie no tempo de Deus. 🙏"},
{numero:425,texto:"Tudo ficará bem. 🤍"},
{numero:426,texto:"Leve essa doçura para outras pessoas. 🍫"},
{numero:427,texto:"A esperança nunca decepciona. 🌷"},
{numero:428,texto:"Seu futuro é brilhante. ⭐"},
{numero:429,texto:"Grandes sonhos começam pequenos. 🌱"},
{numero:430,texto:"A paz é um presente precioso. 🕊️"},
{numero:431,texto:"Continue acreditando em você. 💪"},
{numero:432,texto:"Você merece viver o extraordinário. ✨"},
{numero:433,texto:"Deus está cuidando de tudo. 🙏"},
{numero:434,texto:"A alegria também é uma escolha. 😊"},
{numero:435,texto:"Obrigado por fazer parte da nossa história. 🤎"},
{numero:436,texto:"Que nunca lhe falte fé. 🤍"},
{numero:437,texto:"Você nasceu para vencer. 🏆"},
{numero:438,texto:"Compartilhe um sorriso hoje. ❤️"},
{numero:439,texto:"A Golden Candys acredita em dias felizes. 🍫"},
{numero:440,texto:"Você acabou de adoçar seu dia. 🍬"},
{numero:441,texto:"Que Deus abençoe sua família. 🙏"},
{numero:442,texto:"Você é motivo de orgulho. 💛"},
{numero:443,texto:"Nunca perca sua essência. 🌸"},
{numero:444,texto:"Seu coração merece paz. 🤍"},
{numero:445,texto:"Cada passo importa. 👣"},
{numero:446,texto:"A vida recompensa quem persevera. 🌻"},
{numero:447,texto:"Você inspira pessoas. ✨"},
{numero:448,texto:"A felicidade é contagiante. 😊"},
{numero:449,texto:"Continue fazendo o bem. ❤️"},
{numero:450,texto:"Hoje é um presente. 🎁"},
{numero:451,texto:"Você encontrou uma mensagem exclusiva! 🎉"},
{numero:452,texto:"Esperamos que este brigadeiro tenha feito seu dia melhor. 🍫"},
{numero:453,texto:"Nunca deixe de acreditar em milagres. 🙏"},
{numero:454,texto:"Você é incrível. 💛"},
{numero:455,texto:"Sua luz é necessária. 💡"},
{numero:456,texto:"O amor transforma vidas. ❤️"},
{numero:457,texto:"Tudo coopera para o bem. 🙏"},
{numero:458,texto:"Sorria, você merece. 😊"},
{numero:459,texto:"Continue firme. 💪"},
{numero:460,texto:"Você ainda viverá grandes conquistas. 🏆"},
{numero:461,texto:"Obrigado por escanear nosso QR Code! 📱"},
{numero:462,texto:"Volte para descobrir novas mensagens. 🍫"},
{numero:463,texto:"Quem sabe a próxima será a Mensagem Dourada? 👑"},
{numero:464,texto:"Seu dia merece um toque de doçura. 🍬"},
{numero:465,texto:"Você faz parte da família Golden Candys. 🤍"},
{numero:466,texto:"Que sua semana seja cheia de bênçãos. 🙏"},
{numero:467,texto:"Você consegue! 💛"},
{numero:468,texto:"Nunca desista de você. 🌷"},
{numero:469,texto:"O melhor ainda está por vir. ✨"},
{numero:470,texto:"Obrigado pelo carinho com a Golden Candys. 🍫"},
{numero:471,texto:"Sua alegria vale muito. 😊"},
{numero:472,texto:"Que Deus ilumine seus caminhos. 🙏"},
{numero:473,texto:"Você merece dias leves. 🤍"},
{numero:474,texto:"A vida é mais doce quando compartilhamos. 🍫"},
{numero:475,texto:"Continue espalhando bondade. ❤️"},
{numero:476,texto:"Você faz diferença neste mundo. 🌍"},
{numero:477,texto:"Nunca pare de sonhar grande. ⭐"},
{numero:478,texto:"Sua história será linda. 📖"},
{numero:479,texto:"Você é muito amado. 🤍"},
{numero:480,texto:"Esperamos adoçar seu coração também. 🍫"},
{numero:481,texto:"Obrigado por confiar na Golden Candys. 💛"},
{numero:482,texto:"A felicidade mora nos detalhes. 🌸"},
{numero:483,texto:"Você acabou de encontrar uma mensagem muito rara! 🌟"},
{numero:484,texto:"Leve esperança por onde passar. 🙏"},
{numero:485,texto:"Você é capaz de tudo aquilo que Deus sonhou para você. ❤️"},
{numero:486,texto:"Que nunca faltem motivos para agradecer. 🤍"},
{numero:487,texto:"Aproveite este momento. ☀️"},
{numero:488,texto:"Seu dia ficará ainda melhor. 😊"},
{numero:489,texto:"Você é especial para Deus. 🙏"},
{numero:490,texto:"A Golden Candys deseja ver você novamente em breve! 🍫"},
{numero:491,texto:"Compartilhe essa experiência com alguém especial. ❤️"},
{numero:492,texto:"Seu sorriso vale ouro. ✨"},
{numero:493,texto:"Nunca deixe sua esperança morrer. 🌷"},
{numero:494,texto:"Continue sendo essa pessoa incrível. 💛"},
{numero:495,texto:"A vida é melhor com brigadeiro. 🍫😄"},
{numero:496,texto:"Obrigado por tornar nosso sonho possível. 🤎"},
{numero:497,texto:"Que Deus realize os desejos do seu coração. 🙏"},
{numero:498,texto:"Você acaba de completar uma experiência Golden Candys. ✨"},
{numero:499,texto:"Esperamos que este não seja o último brigadeiro. 🍫😉"},
{numero:500,texto:"🎉 PARABÉNS! Você encontrou a mensagem número 500. Obrigado por fazer parte da história da Golden Candys! 🍫❤️"}.
];

// ==========================
// NÃO ALTERE DAQUI PARA BAIXO
// ==========================

const ganhou = Math.floor(Math.random()*CHANCE_MENSAGEM_DOURADA)==0;

const frase=document.getElementById("frase");
const numero=document.getElementById("numero");
const premio=document.getElementById("premio");

if(ganhou){

const codigo="GC-"+Math.floor(Math.random()*900000+100000);

frase.innerHTML="👑<br><br><strong>VOCÊ ENCONTROU A MENSAGEM DOURADA!</strong>";

numero.innerHTML="";

premio.style.display="block";

premio.innerHTML=`
🎁 <br><br>

Código do prêmio:<br><br>

<b>${codigo}</b>

<br><br>

Apresente este código para ganhar um brigadeiro.

`;

}else{

const sorteio=Math.floor(Math.random()*frases.length);

frase.innerHTML=frases[sorteio].texto;

numero.innerHTML="Mensagem #"+String(frases[sorteio].numero).padStart(3,"0");

}
